/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in real projects and kept here so the skeleton type-checks before first dev run.
